### ISSUE TITLE
The released dataset and the statistical results in the paper are inconsistent

### ISSUE THREAD

**Issue by nttmac** [thecharm/MNRE#1]
Hi,
According to my statistics, there are only 23 relationships (including None) in the released dataset, the number of sentences is 15485 and #Img is 9201. All of them are inconsistent with the statistical results in your paper. 
![image](https://user-images.githubusercontent.com/45266105/122760962-46ed8800-d2ce-11eb-87b3-689dc447ab4b.png)
Could you provide the final version of MNRE?

**Comment by thecharm** [comment]
Thanks for the concern. We have labelled two version of MNRE dataset. The latest is version 2. The dataset mentioned in the ICME paper will be upload soon. We recommend to cite the version 2 of the dataset since we have done a lot of work to refine it. And the corresponding results of version 2 will be reported in a few days.

**Comment by nttmac** [comment]
> Thanks for the concern. We have labelled two version of MNRE dataset. The latest is version 2. The dataset mentioned in the ICME paper will be upload soon. We recommend to cite the version 2 of the dataset since we have done a lot of work to refine it. And the corresponding results of version 2 will be reported in a few days.

Thank you for the detailed explanation!

**Comment by nttmac** [comment]
> Thanks for the concern. We have labelled two version of MNRE dataset. The latest is version 2. The dataset mentioned in the ICME paper will be upload soon. We recommend to cite the version 2 of the dataset since we have done a lot of work to refine it. And the corresponding results of version 2 will be reported in a few days.

Hi,
Could you provide the visual features extracted by the pre-trained object detector?

**Comment by thecharm** [comment]
We have updated the data and you can download the visual features in the Version-1 dir.
